import davidVassalluzzoPhoto from './assets/david-vassalluzzo.jpg'
import joanneDingPhoto from './assets/joanne-ding.jpg'
import johnLockwoodPhoto from './assets/john-lockwood.jpg'
import sydneyRondeauPhoto from './assets/sydney-rondeau.jpg'
import tyroneSerapioPhoto from './assets/tyrone-serapio.jpg'
import salmanAjiPhoto from './assets/salman-aji.png'
import mehdiAtmaniPhoto from './assets/mehdi-atmani.jpg'
import ashleyLuoPhoto from './assets/ashley-luo.jpg'

export const sections = [
  {
    id: 'about',
    number: '01',
    label: 'About',
    eyebrow: 'CSCI 0410 / CSCI 1411',
    title: 'CSCIO41O',
    body: 'A broad coverage of core topics in AI as a prelude to students taking more in-depth AI courses later on. Throughout the course, you will study key AI models, reinforcement learning, and both supervised and unsupervised machine learning to build socially responsible AI.',
    meta: ['Prof. Amy Greenwald', 'Brown University', 'Fall 2026'],
    accent: '#f4c84a',
    action: 'View assignments',
  },
  {
    id: 'homework',
    number: '02',
    label: 'Homework',
    title: 'Homework',
    table: {
      caption: 'Homework is released at 2:00 PM ET and is due at 11:59 PM ET.',
      columns: ['Homework', 'Out', 'Due'],
      rows: [
        ['Homework 1: Uninformed Search', '9/10', '9/20'],
        ['Homework 2: Informed Search', '9/15', '9/20'],
        ['Homework 3: Adversarial Search', '9/22', '9/28'],
        ['Homework 4: SAT', '9/29', '10/5'],
        ['Homework 5: Constrained Optimization', '10/13', '10/19'],
        ['Homework 6: Linear Regression', '10/20', '10/26'],
        ['Homework 7: Neural Networks', '10/27', '11/2'],
        ['Homework 8: Reinforcement Learning', '11/10', '11/16'],
        ['Final Project: Part 1', '11/17', '11/23'],
        ['Final Project: Part 2', '11/30', '12/7'],
      ],
    },
    accent: '#ff7d5c',
    action: 'Browse lectures',
  },
  {
    id: 'lectures',
    number: '03',
    label: 'Lectures',
    eyebrow: 'The course path',
    title: 'Lectures',
    body: 'The semester begins with classical search and logic, crosses probability and optimization, then builds toward supervised learning, deep learning, MDPs, reinforcement learning, clustering, and Monte Carlo tree search.',
    meta: ['Search + logic', 'Machine learning', 'Sequential decisions'],
    table: {
      variant: 'lectures',
      columns: ['Lecture', 'Date', 'Readings', 'Notes / Resources'],
      rows: [
        ['Introduction to AI', '9/9', '-', '-'],
        ['Search Problems: Blind Search (BFS, DFS, Iterative Deepening)', '9/11', '-', '-'],
        ['Heuristic Search', '9/14', '-', '-'],
        ['Optimal Search (A*)', '9/16', '-', '-'],
        ['Adversarial Search', '9/18', '-', '-'],
        ['Discrete Optimization', '9/21', '-', '-'],
        ['Propositional Logic, SAT, NP-Completeness, CNFs', '9/23', '-', '-'],
        ['CSPs: GSAT, WALKSAT, N-Queens', '9/25', '-', '-'],
        ['Predicate Calculus + Planning', '9/28', '-', '-'],
        ['Continuous Optimization', '9/30', '-', '-'],
        ['Convexity', '10/2', '-', '-'],
        ['Constrained Optimization (Modeling)', '10/5', '-', '-'],
        ['Continuous Optimization (PGD + Lagrangians)', '10/7', '-', '-'],
        ['Midterm 1', '10/9', '-', '-'],
        ['No Class', '10/12', '-', '-'],
        ['Intro to Supervised Learning', '10/14', '-', '-'],
        ['Linear Regression', '10/16', '-', '-'],
        ['Bias and Variance Tradeoff', '10/19', '-', '-'],
        ['Logistic Regression and Entropy', '10/21', '-', '-'],
        ['Perceptrons', '10/23', '-', '-'],
        ['MLPs and Backpropagation', '10/26', '-', '-'],
        ['Deep Learning', '10/28', '-', '-'],
        ['Markov Reward Processes, Value Functions', '10/30', '-', '-'],
        ['Markov Decision Processes, Policy Evaluation, Q-functions', '11/2', '-', '-'],
        ['Value Iteration (Dynamic Programming)', '11/4', '-', '-'],
        ['Q-Learning', '11/6', '-', '-'],
        ['Midterm 2', '11/9', '-', '-'],
        ['Final Project: Go + MCTS', '11/11', '-', '-'],
        ['AlphaGo: MCTS + Learning', '11/13', '-', '-'],
        ['Iterative Deepening Review', '11/16', '-', '-'],
        ['Probability Review + Bayesian networks', '11/18', '-', '-'],
        ['Bayesian networks + Naive Bayes', '11/20', '-', '-'],
        ['Language Models', '11/23', '-', '-'],
        ['No Class (Thanksgiving)', '11/25', '-', '-'],
        ['No Class (Thanksgiving)', '11/27', '-', '-'],
        ['PCA + Linear Algebra Review', '11/30', '-', '-'],
        ['K-Means + Facility Location', '12/2', '-', '-'],
        ['GMMs + Probability review (Normal Distribution, MLE)', '12/4', '-', '-'],
      ],
    },
    accent: '#7dc8ff',
    action: 'Check the calendar',
  },
  {
    id: 'calendar',
    number: '04',
    label: 'Calendar',
    eyebrow: 'Plan your semester',
    title: 'Calendar',
    embedUrl: 'https://calendar.google.com/calendar/embed?src=c_641b9f9a16d4438d5555460da49a8e42d6a3e69fec7e24282c92a452a6fc1268%40group.calendar.google.com&ctz=America%2FNew_York',
    meta: ['M / W / F lectures', 'Released 2 PM ET', 'Due 11:59 PM ET'],
    accent: '#b8de6f',
    action: 'Find a discussion',
  },
  {
    id: 'discussion',
    number: '05',
    label: 'Discussion',
    eyebrow: 'Connect ideas to impact',
    title: 'Sections',
    body: 'Discussion sections pair assignment support with questions about AI policy, bias in data, automated decision-making, innovation, and fairness across groups.',
    meta: ['Slides + activities', 'Weekly quizzes', 'Assignment support'],
    table: {
      variant: 'discussion',
      linkColumns: [0],
      columns: ['Topic', 'Materials', 'Date'],
      rows: [
        ['AI Policy', 'Slides · Quiz', '2/2 – 2/6'],
        ['HW 1 and 2', 'Slides · Quiz', '2/9 – 2/13'],
        ['Bias in Data', 'Slides · Quiz', '2/23 – 2/27'],
        ['HW 3 and 4', 'Slides · Quiz', '3/2 – 3/6'],
        ['Automated Decision-Making', 'Slides · Quiz', '3/9 – 3/13'],
        ['HW 5 and 6', 'Slides · Quiz', '3/16 – 3/20'],
        ['AI Innovation: Accels vs. Decels', 'Slides · Quiz', '3/30 – 4/3'],
        ['Aggregation Bias / Fairness', 'Slides · Quiz', '4/6 – 4/10'],
        ['HW 7, 8 and 9', 'Slides · Quiz', '4/13 – 4/17'],
      ],
    },
    accent: '#d2a8ff',
    action: 'Meet the staff',
  },
  {
    id: 'staff',
    number: '06',
    label: 'Staff',
    title: 'Staff',
    members: [
      { id: 'professor', name: 'Amy Greenwald', role: 'Professor', image: null, hometown: '', bio: "", shirt: '#ff6b57', detail: '#143a58', skin: '#d7a06f', hair: '#3e2a22' },
      { id: 'head-ta-1', name: 'Salman Aji', role: 'HTA', image: salmanAjiPhoto, hometown: 'Latakia, Syria', bio: "Hey! I'm Salman, and I'm a senior from Syria studying CS and APMA. In my free time, I love to play Minecraft, watch a sitcom (currently looking for one to watch next), or hike! Super excited to meet you all :)", shirt: '#f4c84a', detail: '#ca6a36', skin: '#9a6048', hair: '#241e20' },
      { id: 'head-ta-2', name: 'Mehdi Atmani', role: 'HTA', image: mehdiAtmaniPhoto, hometown: 'Casablanca, Morocco', bio: "Hi! I’m Mehdi, a senior double majoring in Computer Science and APMA–Econ. Outside of school, I enjoy playing poker, building in Minecraft, and going on side quests. Super excited to meet you all!", shirt: '#5cb9e8', detail: '#194a72', skin: '#efbd8e', hair: '#72503b' },
      { id: 'sta-uta', name: 'Myan Nguyen', role: 'Joint STA/UTA', image: null, hometown: 'Westbrook, Connecticut', bio: "Hey everyone! I'm a senior studying Computer Science. Outside of the CIT, you can usually find me in Ceremony, playing tennis or spikeball, or on a walk around College Hill!", shirt: '#a8df63', detail: '#426f3b', skin: '#bd7f5c', hair: '#342824' },
      { id: 'uta-1', name: 'Ashley Luo', role: 'UTA', image: ashleyLuoPhoto, hometown: 'Weston', bio: "I love watercolor and sewing! And I cannot wiggle my eyebrows at all.", shirt: '#d2a8ff', detail: '#624c98', skin: '#e1ad7d', hair: '#2a2029' },
      { id: 'uta-2', name: 'David Vassalluzzo', role: 'UTA', image: davidVassalluzzoPhoto, hometown: 'Boca Raton, FL', bio: "Hello everyone! I'm David Vassalluzzo, a junior from Boca Raton, Florida, studying APMA-CS. I love all things AI and playing and watching sports, so feel free to chat with me about that. I'm looking forward to meeting all of you.", shirt: '#ff9eb5', detail: '#9e4763', skin: '#8e563e', hair: '#16191b' },
      { id: 'uta-3', name: 'Joanne Ding', role: 'UTA', image: joanneDingPhoto, hometown: 'Shanghai, China', bio: "Hi! I'm a junior studying Math-CS. Outside of class, I enjoy exploring Providence, browsing the stacks at the Orwig Music Library, and playing the flute. Excited to meet everyone!", shirt: '#78d8c4', detail: '#25766e', skin: '#efc39c', hair: '#bc7a3e' },
      { id: 'uta-4', name: 'John Lockwood', role: 'UTA', image: johnLockwoodPhoto, hometown: 'Milford, PA', bio: "Hi! I'm a senior studying applied math and computer science. I like to swim, play piano, play video games, and listen to music.", shirt: '#ff9a58', detail: '#934423', skin: '#b97452', hair: '#37251f' },
      { id: 'uta-5', name: 'Sydney Rondeau', role: 'UTA', image: sydneyRondeauPhoto, hometown: 'Cherry Hill, NJ', bio: "Hi! I'm a junior studying Apma-Bio. I love going to the gym, playing soccer, reading, and Drake Maye. I'm so excited for this semester and can't wait to meet you all!", shirt: '#7ea7ff', detail: '#344f9c', skin: '#f1c6a0', hair: '#4d3428' },
      { id: 'uta-6', name: 'Tyrone Serapio', role: 'UTA', image: tyroneSerapioPhoto, hometown: 'San Juan, Philippines', bio: "Hi! I’m Tyrone. I like learning card tricks and cardistry. Really looking forward to meet you all! ", shirt: '#d7e65b', detail: '#647529', skin: '#774a38', hair: '#171719' },
    ],
    accent: '#ff9eb5',
    action: 'Open resources',
  },
  {
    id: 'resources',
    number: '07',
    label: 'Resources',
    eyebrow: 'Keep these close',
    title: 'Resources',
    meta: ['Course missive', 'Code + debugging', 'Python guides'],
    links: [
      { label: 'Course Missive', href: 'https://hackmd.io/eFzIAJmCTtW0fUGJ4w5xOg' },
      { label: 'EdStem Discussion', href: 'https://edstem.org/us/courses/93617' },
      { label: 'Testing Guide', href: 'https://hackmd.io/@cs410/SyDy2CVnA' },
    ],
    accent: '#78d8c4',
    action: 'Back to course intro',
  },
]
