export const sections = [
  {
    id: 'home',
    number: '01',
    label: 'Start here',
    eyebrow: 'An interactive digital studio',
    title: 'Make your next move count.',
    body: 'We build playful digital experiences that turn curious visitors into active participants. Take a hop to see how we work.',
    meta: ['Strategy', 'Design', 'Development'],
    accent: '#f4c84a',
    action: 'Hop to explore',
  },
  {
    id: 'about',
    number: '02',
    label: 'About',
    eyebrow: 'Small team · big range',
    title: 'Built for the curious.',
    body: 'We are an independent creative team mixing design, storytelling, and technology. Every project starts with a sharp idea and ends with something people want to use.',
    meta: ['Providence', 'Working worldwide', 'Since 2026'],
    accent: '#ff7d5c',
    action: 'Keep crossing',
  },
  {
    id: 'work',
    number: '03',
    label: 'Selected work',
    eyebrow: 'Recent crossings',
    title: 'Ideas with somewhere to go.',
    body: 'Identity systems, launch sites, experiments, and products—designed as connected experiences rather than isolated deliverables.',
    meta: ['North / Identity', 'Fieldnote / Product', 'Afterdark / Web'],
    accent: '#7dc8ff',
    action: 'See our approach',
  },
  {
    id: 'services',
    number: '04',
    label: 'Services',
    eyebrow: 'How we help',
    title: 'From first sketch to launch day.',
    body: 'We join at the messy beginning, bring shape to the opportunity, then design and build the real thing with your team.',
    meta: ['Brand direction', 'Web design', 'Creative code'],
    accent: '#b8de6f',
    action: 'One more hop',
  },
  {
    id: 'contact',
    number: '05',
    label: 'Contact',
    eyebrow: 'You made it across',
    title: 'Let’s make something worth crossing for.',
    body: 'Have a project, a strange idea, or just a good question? We would love to hear where you are headed.',
    meta: ['hello@crossing.studio', 'New projects · Fall 2026'],
    accent: '#d2a8ff',
    action: 'Start again',
  },
]
