import davidVassalluzzoPhoto from './assets/david-vassalluzzo.jpg'
import joanneDingPhoto from './assets/joanne-ding.jpg'
import johnLockwoodPhoto from './assets/john-lockwood.jpg'
import sydneyRondeauPhoto from './assets/sydney-rondeau.jpg'
import tyroneSerapioPhoto from './assets/tyrone-serapio.jpg'
import salmanAjiPhoto from './assets/salman-aji.png'
import mehdiAtmaniPhoto from './assets/mehdi-atmani.jpg'
import ashleyLuoPhoto from './assets/ashley-luo.jpg'
import myanNguyenPhoto from './assets/myan-nguyen.jpg'
import chickenPhoto from './assets/chicken.png'
import { lectureMaterialsForDate } from './lectureMaterials'

export const sections = [
  {
    id: 'about',
    number: '01',
    label: 'About',
    eyebrow: 'CSCI 0410 / CSCI 1411',
    title: 'CSCIO41O',
    body: "A broad coverage of core topics in AI as a prelude to students taking more in-depth AI courses later on. Students will study key AI models and machine learning, en route to building socially responsible AI.",
    meta: ['Prof. Amy Greenwald', 'Brown University', 'Fall 2026'],
    accent: '#f4c84a',
    action: 'Browse lectures',
  },
  {
    id: 'lectures',
    number: '02',
    label: 'Lectures',
    eyebrow: 'The course path',
    title: 'Lectures',
    body: 'The semester begins with classical search and logic, crosses probability and optimization, then builds toward supervised learning, deep learning, MDPs, reinforcement learning, clustering, and Monte Carlo tree search.',
    meta: ['Search + logic', 'Machine learning', 'Sequential decisions'],
    table: {
      variant: 'lectures',
      columns: ['Date', 'Lecture', 'Notes', 'Resources'],
      rows: [
        ['Welcome', '9/9', '-'],
        ['Uniformed Search', '9/11', '-'],
        ['Heuristic Search', '9/14', '-'],
        ['A* Search', '9/16', '-'],
        ['Adversarial Search', '9/18', '-'],
        ['Discrete Optimization', '9/21', '-'],
        ['Propositional Logic', '9/23', '-'],
        ['SAT', '9/25', '-'],
        ['Planning', '9/28', '-'],
        ['Continuous Optimization', '9/30', '-'],
        ['Continuous Optimization', '10/2', '-'],
        ['Constrained Optimization', '10/5', '-'],
        ['Constrained Optimization', '10/7', '-'],
        ['Midterm 1', '10/9', '-'],
        ['No Class', '10/12', '-'],
        ['Supervised Learning', '10/14', '-'],
        ['Linear Regression', '10/16', '-'],
        ['Bias Variance Tradeoff', '10/19', '-'],
        ['Logistic Regression', '10/21', '-'],
        ['Simple Perceptrons', '10/23', '-'],
        ['Multilayer Perceptrons', '10/26', '-'],
        ['Fairness', '10/28', '-'],
        ['Markov Processes', '10/30', '-'],
        ['Markov Decisions Processes', '11/2', '-'],
        ['Dynamic Programming', '11/4', '-'],
        ['Reinforcement Learning', '11/6', '-'],
        ['Midterm 2', '11/9', '-'],
        ['Final Project: Go', '11/11', '-'],
        ['Monte Carlo Tree Search', '11/13', '-'],
        ['AlphaGo', '11/16', '-'],
        ['Bayesian Networks', '11/18', '-'],
        ['Naive Bayes', '11/20', '-'],
        ['LLMs', '11/23', '-'],
        ['No Class', '11/25', '-'],
        ['No Class', '11/27', '-'],
        ['Guest Lecture', '11/30', '-'],
        ['Guest Lecture', '12/2', '-'],
        ['Guest Lecture', '12/4', '-'],
      ].map(([lecture, date]) => {
        const materials = lectureMaterialsForDate(date)
        return [
          date,
          lecture,
          materials.notes,
          materials.resources,
        ]
      }),
    },
    accent: '#7dc8ff',
    action: 'View assignments',
  },
  {
    id: 'homework',
    number: '03',
    label: 'Homework',
    title: 'Homework',
    table: {
      variant: 'homework',
      columns: ['Homework', 'Out', 'Due', 'Code Review Sign Up'],
      links: {
        'Homework 1: Uninformed Search': 'https://hackmd.io/@cs410/SkUv4EDuMx',
      },
      rows: [
        ['Homework 1: Uninformed Search', '9/10', '9/20', '-'],
        ['Homework 2: Informed Search', '9/15', '9/20', '-'],
        ['Homework 3: Adversarial Search', '9/22', '9/28', '-'],
        ['Homework 4: SAT', '9/29', '10/5', '-'],
        ['Homework 5: Constrained Optimization', '10/13', '10/19', '-'],
        ['Homework 6: Linear Regression', '10/20', '10/26', '-'],
        ['Homework 7: Neural Networks', '10/27', '11/2', '-'],
        ['Homework 8: Reinforcement Learning', '11/10', '11/16', '-'],
        ['Homework 9: Bayesian Networks', '11/24', '12/4', '-'],
        ['Homework 10: LLMs and PDDL (Optional)', '12/1', '12/11', '-'],
        ['Final Project: Part 1', '11/17', '11/23', '-'],
        ['Final Project: Part 2', '11/30', '12/7', '-'],
        ['Final Project: Part 3', '12/4', '-', '-'],
      ],
    },
    accent: '#ff7d5c',
    action: 'Find a discussion',
  },
  {
    id: 'discussion',
    number: '04',
    label: 'Discussion',
    eyebrow: 'Connect ideas to impact',
    title: 'Sections',
    body: 'Discussion sections pair assignment support with questions about AI policy, bias in data, automated decision-making, innovation, and fairness across groups.',
    meta: ['Slides + activities', 'Weekly quizzes', 'Assignment support'],
    table: {
      variant: 'discussion',
      columns: ['Topic', 'Materials', 'Date'],
      rows: [
        ['SRC: AI Policy', '-', '9/14 – 9/18'],
        ['Conceptual: HW1 and HW2', '-', '9/21 – 9/25'],
        ['SRC: Automated Decision-Making', '-', '9/28 – 10/2'],
        ['Conceptual: HW3 and HW4', '-', '10/5 – 10/9'],
        ['SRC: Acceleration and Deceleration', '-', '10/12 – 10/16'],
        ['Conceptual: HW5 and HW6', '-', '10/19 – 10/23'],
        ['SRC: Bias in Data', '-', '10/26 – 10/30'],
        ['Conceptual: HW7', '-', '11/2 – 11/6'],
        ['SRC: Hands-on Workshop', '-', '11/9 – 11/13'],
        ['Conceptual: HW8 and HW9', '-', '11/30 – 12/4'],
      ],
    },
    accent: '#d2a8ff',
    action: 'Check the calendar',
  },
  {
    id: 'calendar',
    number: '05',
    label: 'Calendar',
    eyebrow: 'Plan your semester',
    title: 'Calendar',
    embedUrl: 'https://calendar.google.com/calendar/embed?src=c_641b9f9a16d4438d5555460da49a8e42d6a3e69fec7e24282c92a452a6fc1268%40group.calendar.google.com&ctz=America%2FNew_York',
    meta: ['M / W / F lectures', 'Released 2 PM ET', 'Due 11:59 PM ET'],
    accent: '#b8de6f',
    action: 'Meet the staff',
  },
  {
    id: 'staff',
    number: '06',
    label: 'Staff',
    title: 'Staff',
    members: [
      { id: 'professor', name: 'Amy Greenwald', role: 'Professor', image: chickenPhoto, hometown: 'Providence, RI', bio: "Hi! My name is Amy, and I've been a Brown prof for longer than most of the students in this class have been alive. Throughout my career, I've taught intro AI and intro CS (with the aim of teaching students to program functionally, not dysfunctionally), Internet Agent Economics, and Algorithmic Game Theory. My research area is AI, specifically multi-agent systems, which concerns autonomous agent and system design for effective agent interaction. On the rare occasions when I'm not busy at work, I enjoy sports: soccer, biking, tennis, ice hockey, and more!", shirt: '#ff6b57', detail: '#143a58', skin: '#d7a06f', hair: '#3e2a22' },
      { id: 'head-ta-1', name: 'Salman Aji', role: 'HTA', image: salmanAjiPhoto, hometown: 'Latakia, Syria', bio: "Hey! I'm Salman, and I'm a senior from Syria studying CS and APMA. In my free time, I love to play Minecraft, watch a sitcom (currently looking for one to watch next), or hike! Super excited to meet you all :)", shirt: '#f4c84a', detail: '#ca6a36', skin: '#9a6048', hair: '#241e20' },
      { id: 'head-ta-2', name: 'Mehdi Atmani', role: 'HTA', image: mehdiAtmaniPhoto, hometown: 'Casablanca, Morocco', bio: "Hi! I’m Mehdi, a senior double majoring in Computer Science and APMA–Econ. Outside of school, I enjoy playing poker, building in Minecraft, and going on side quests. Super excited to meet you all!", shirt: '#5cb9e8', detail: '#194a72', skin: '#efbd8e', hair: '#72503b' },
      { id: 'sta-uta', name: 'Myan Nguyen', role: 'Joint STA/UTA', image: myanNguyenPhoto, hometown: 'Westbrook, CT', bio: "Hey everyone! I'm a senior studying Computer Science. Outside of the CIT, you can usually find me in Ceremony, playing tennis or spikeball, or on a walk around College Hill!", shirt: '#a8df63', detail: '#426f3b', skin: '#bd7f5c', hair: '#342824' },
      { id: 'uta-1', name: 'Ashley Luo', role: 'UTA', image: ashleyLuoPhoto, hometown: 'Weston', bio: "I love watercolor and sewing! And I cannot wiggle my eyebrows at all.", shirt: '#d2a8ff', detail: '#624c98', skin: '#e1ad7d', hair: '#2a2029' },
      { id: 'uta-2', name: 'David Vassalluzzo', role: 'UTA', image: davidVassalluzzoPhoto, hometown: 'Boca Raton, FL', bio: "Hello everyone! I'm David Vassalluzzo, a junior from Boca Raton, Florida, studying APMA-CS. I love all things AI and playing and watching sports, so feel free to chat with me about that. I'm looking forward to meeting all of you.", shirt: '#ff9eb5', detail: '#9e4763', skin: '#8e563e', hair: '#16191b' },
      { id: 'uta-3', name: 'Joanne Ding', role: 'UTA', image: joanneDingPhoto, hometown: 'Shanghai, China', bio: "Hi! I'm a junior studying Math-CS. Outside of class, I enjoy exploring Providence, browsing the stacks at the Orwig Music Library, and playing the flute. Excited to meet everyone!", shirt: '#78d8c4', detail: '#25766e', skin: '#efc39c', hair: '#bc7a3e' },
      { id: 'uta-4', name: 'John Lockwood', role: 'UTA', image: johnLockwoodPhoto, hometown: 'Milford, PA', bio: "Hi! I'm a senior studying applied math and computer science. I like to swim, play piano, play video games, and listen to music.", shirt: '#ff9a58', detail: '#934423', skin: '#b97452', hair: '#37251f' },
      { id: 'uta-5', name: 'Sydney Rondeau', role: 'UTA', image: sydneyRondeauPhoto, hometown: 'Cherry Hill, NJ', bio: "Hi! I'm a junior studying Apma-Bio. I love going to the gym, playing soccer, reading, and Drake Maye. I'm so excited for this semester and can't wait to meet you all!", shirt: '#7ea7ff', detail: '#344f9c', skin: '#f1c6a0', hair: '#4d3428' },
      { id: 'uta-6', name: 'Tyrone Serapio', role: 'UTA', image: tyroneSerapioPhoto, hometown: 'San Juan, Philippines', bio: "Hi! I’m Tyrone. I like learning card tricks and cardistry. Really looking forward to meet you all! ", shirt: '#d7e65b', detail: '#647529', skin: '#774a38', hair: '#171719' },
    ],
    accent: '#ff9eb5',
    action: 'Open resources',
  },
  {
    id: 'resources',
    number: '07',
    label: 'Resources',
    eyebrow: 'Keep these close',
    title: 'Resources',
    resourceGroups: [
      {
        title: 'Course Policies',
        items: [
          { label: 'Course Missive', href: 'https://hackmd.io/BYFMfsT1Qm-KryUFKOfBYA' },
        ],
      },
      {
        title: 'Python and HW Guides',
        items: [
          { label: 'Testing Guide', href: 'https://docs.google.com/document/d/1otaPyhze73Qv6GMfuddAoTQJg10a5Fj8ICOaEraqBtA/edit?tab=t.0#heading=h.60udf8bnil5l' },
          { label: 'Python Set Up', href: 'https://hackmd.io/@cs410/BJvhqHXuR' },
        ],
      },
      {
        title: 'General Resources',
        items: [
          { label: 'EdStem', href: 'https://edstem.org/us/courses/105523/discussion' },
          { label: 'Gradescope', detail: 'Code: YG7YZZ' },
        ],
      },
    ],
    accent: '#78d8c4',
    action: 'Back to course intro',
  },
]
